<a href="https://colab.research.google.com/github/Aranagut/5502-lab-assignment-1/blob/main/Lab_Assignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third Lab-assignment (02/10/2022, 50 points in total)

The purpose of this exercise is to understand users' information needs, then collect data from different sources for analysis.

Question 1 (10 points). Fomulate your domain problem: Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

In [ ]:
# 1) Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

Domain problem: 
> Domain problem is to collect the data that obtained from the twitter tweets on Ukraine hastag.

> Research question is to Analyse the Topic Modelling/clustering of the data.
> We retrive the data of Ukraine key word tagged by users.
> Here we analyze the data based on the tags.
> The explanatory data analysis are on user names, posted time, and key word (tags) of Ukraine name.

Data Required to answer the questions:
> tweepy and pandas libraries are used.
> Attributes used to answer the research question are User Names, Posted Time and the Text.

I have collected the data from the following link: 

Steps for collecting and saving the data:
> Web scraping technique is used to scrape the data.
> Web Scraping is performed by using tweepy and pandas libraries.
> Each twitter page is scraped to retrive the information.
> User names, Tweet posted time and Text of the tags is collected from Twitter and store the data into CSV file.
> Here we are going to analyze the data who have used.

'''

Question 2 (10 points). Collect your data to answer the research problem: Write python code to collect 1000 data samples you discussed above.

In [2]:
# 2) You code here (Please add comments in the code):

#Importing required libraries
import tweepy as tw
import pandas as pd

Key = 'u7L1lnR7HN85dn1qnTFO1cegb'
Secret = 'QN1JrEmit2To46ZcwWAT4aI5QGWZXWRDDUPnMCWV5M66SFc8wT'

Auth = tw.OAuthHandler(Key, Secret)
Api = tw.API(Auth, wait_on_rate_limit=True)
Hashtag = "#Ukraine"

Twitter_tweets = tw.Cursor(Api.search, q=Hashtag, lang="en").items(1000)
#Printing tweets
Movie_tweets = [[tweet.user.screen_name,tweet.created_at, tweet.text] for tweet in Twitter_tweets]
#Converting data into CSV file
Twitter_Movie_tweets = pd.DataFrame(data=Movie_tweets, columns=['User_name','Posted_time', 'Text'])
Twitter_Movie_tweets.to_csv("Avenger_tweets.csv")
Twitter_Movie_tweets

           User_name  ...                                               Text
0      LuxenhoferLab  ...  RT @ernabodstrom: Are you a Ukrainian seeking ...
1      normundsbergs  ...  RT @DariaSipigina: SOUND ON.\n\nThis is what o...
2          MANRESuhh  ...  RT @Pontifex: I renew my invitation for everyo...
3          AGfarAWAY  ...  RT @With__Ukraine: The entire stadium in #Lisb...
4      LillyBell0115  ...  RT @FeWoessner: Germany ðŸ‡©ðŸ‡ª delivers Stinger mi...
..               ...  ...                                                ...
995        titoperez  ...  RT @TigayBarry: Press interviews #Ukraine Pres...
996  Lekatit11Tigray  ...  We #Tigrayans as victims of long war are pleas...
997        RAINY9586  ...  RT @LawrenceSellin: The longer Kyiv holds out,...
998       bong8242co  ...  RT @_universalstory: This is Stanislav Petrov....
999  pasassezdetemps  ...  RT @voidalerts: ðŸš¨ Massive protests in Moscow. ...

[1000 rows x 3 columns]

Question 3 (10 points). Understand the data quality: Search a second hand dataset (any dataset) from kaggle or other websites. Describe the data quality problem of the dataset and explain your strtegy to clean the data.

In [ ]:
# 3) Your answer here (no code for this question, write down your answer as detail as possible for the above questions):
'''

Please write you answer here:

> I have considered the data of Data Cleaning Challenge: Handling missing values from Keggle.

Dataset Link:
https://www.kaggle.com/rtatman/data-cleaning-challenge-handling-missing-values
> In this data set we have few columns that are included like 
Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, Playtimediff, Sideoffield.

Steps to clean the data:
>Take a first look at the data - The first thing we'll need to do is load in the libraries and datasets we'll be using.
> The first thing I do when I get a new dataset is take a look at some of it. This lets me see that it all read in correctly and get an idea of what's going on with the data. 
> In this case, I'm looking to see if I see any missing values, which will be reprsented with NaN or None.
> See how many missing data points we have in each column.
> Figure out why the data is missing.
> Next, we need to Drop missing values.
> Then Filling in missing values automatically.

'''

Question 4 (20 points). Data cleaning: There are two datasets TwADR-L (from Twitter) and AskAPatient (Link: https://zenodo.org/record/55013#.YgU2NN-ZO4T) for medical concept
normalization. However, the two datasets have serious data quality problems. Please read the introduction of the datasets and clean the two datasets by following the steps in the statement.

In the original dataset, the TwADR-L had 48,057 training, 1,256 validation and 1,427 test examples. The test set (all
test samples from 10 folds combined) consists of 765 unique phrases and 273 unique classes (medical concepts). The AskAPatient dataset contained 156,652 training, 7,926 validation, and 8,662 test examples. The entire test set (all test samples
from 10 folds combined) consists of 3,749 unique phrases and 1,035 unique classes (medical concepts). The authors
randomly split each dataset into ten equal folds, ran 10-fold cross validation and reported the accuracy averaged across the
ten folds. 

We found that, in the original data set, many phrase-label pairs appeared multiple times within the same training data file
and also across the training and test data sets in the same fold. In the AskAPatient data set, on average 35.82% of the test data overlapped with training data in the same fold. In the Twitter (TwADR-L) dataset, on average 8.62% of the test set had an overlap with the training data in the same fold. Having a large overlap between the training and the test data can potentially
introduce bias in the model and contribute to high accuracy. It is not unlikely that the high model performance reported in the original paper may be triggered by the the large overlap between the training and test sets.

Therefore to remove the bias, we further cleaned and recreated the training, validation, and test sets such that each
phrase-label pair appears only once in the entire dataset (either in training, validation or test set).

(1) First, we combined all examples in training, validation and test data from the original data set and then removed all
duplicate phrase-label pairs (examples that have the same phrase and label pair and appear more than once in training/validation/test datasets). Table II shows the statistics of the new dataset (after removing duplicates). The Twitter data set had 3,157 unique phrase-label pairs and 2,220 unique labels (medical concepts) while 173 phrases had multiple labels (i.e., they were assigned to more than one label). Many concepts had only one example, and the concept that had the most number
of examples had 36 phrases. On average, each concept had 1.42 examples. The AskAPatient data set had 4,496 unique phrase-label pairs, 1,036 unique labels while 26 phrases had multiple labels. Table III shows examples of phrases that had multiple labels. For example, â€˜madâ€™ can be mapped to â€˜angerâ€™ or â€˜rageâ€™ and â€˜soreâ€™ can be mapped to â€˜painâ€™ or â€˜myalgiaâ€™.

(2) Second, we remove all concepts that had less than five examples. The statistics of the final data are shown in Table IV.

(3) Third, we divide all examples without multiple labels into random 10 folds such that each unique phrase-label pair
appears once in one of the 10 test sets. We add the pairs with multiple labels into the training data. This final 10-folds
dataset is used in all our experiments.

(The original paper can be download on canvas)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
#1)

import glob
import pandas as pd
result_df =  pd.DataFrame()
# we iterate through both datasets 
for dataset in ['TwADR-L', 'AskAPatient']:
    result = {}
    df = pd.DataFrame()
    for filepath in glob.glob('/content/drive/MyDrive/datasets/{}/*.txt'.format(dataset)):
        data = pd.read_csv(filepath, sep = "\t", header = None, encoding= 'unicode_escape')
        df = df.append(data)
    # we create combined dataframe by combining Each dataset text files.
    df = df.reset_index(drop=True)
    df['phrase_label'] = df[1] + " " + df[2]
    df.columns = ['id', 'labels', 'phrases', 'phrase-label']
    # type casting to str
    df = df.astype({"id": str})
    # converting all values to lower case
    for columns in df.columns:
        df[columns] = df[columns].str.lower() 

    # dropping duplicates
    df = df.drop_duplicates('phrase-label')

    # storing results of the table in dictionary
    result['Unique_phrases'] = len(df['phrases'].unique())
    result['Unique_labels'] = len(df['labels'].unique())
    result['Unique_phrase_label_pairs'] = df.shape[0]
    df1 = pd.DataFrame(df['phrases'].value_counts())
    result['Phrases with multiple labels'] = df1[df1['phrases'] > 1].shape[0]
    result['Min examples per label'] = df['labels'].value_counts().values.min()
    result['Max examples per label'] = df['labels'].value_counts().values.max()
    result['Avg examples per label'] = round(df['labels'].value_counts().mean(), 2)
    result_df = result_df.append(result, ignore_index=True)


result_df = result_df.T
result_df = result_df.astype({0: int, 1: int})
result_df.columns = ['TwADR-L', 'AskAPatient']

result_df

                              TwADR-L  AskAPatient
Unique_phrases                   2944         4470
Unique_labels                    2220         1038
Unique_phrase_label_pairs        3157         4507
Phrases with multiple labels      173           35
Min examples per label              1            1
Max examples per label             36          141
Avg examples per label              1            4

In [5]:
#(2) Second, we remove all concepts that had less than five examples. The statistics of the final data are shown in Table IV.
import pandas as pd
import glob
result_df = pd.DataFrame()
# Here, we iterate through both datasets 
for dataset in ['TwADR-L', 'AskAPatient']:
    df = pd.DataFrame()
    result = {}
    for filepath in glob.glob('/content/drive/MyDrive/datasets/{}/*.txt'.format(dataset)):
        #print(filepath)
        data = pd.read_csv(filepath, sep = "\t", header = None, encoding= 'unicode_escape')
        df = df.append(data)
    # we create combined dataframe by combining Each dataset by text files.
    df = df.reset_index(drop=True)
    df['phrase_label'] = df[1] + " " + df[2]
    df.columns = ['id', 'labels', 'phrases', 'phrase-label']
    #print(df.shape)
    df = df.astype({"id": str})
    # converting to lower case
    for columns in df.columns:
        df[columns] = df[columns].str.lower() 

    # we drop duplicates that are phrase-label pairs... 
    df = df.drop_duplicates('phrase-label')

    index_list = []
    for i in range(df.shape[0]):
        if df['labels'].value_counts()[df.iloc[i]['labels']] < 5:
            index_list.append(i)

    # we drop the labels that have less than count of 5.
    df.drop(df.index[index_list], inplace=True)
    result = {}
    # storing results of the table in dictionary
    result['Unique_phrases'] = len(df['phrases'].unique())
    result['Unique_labels'] = len(df['labels'].unique())
    result['Unique_phrase_label_pairs'] = df.shape[0]
    df1 = pd.DataFrame(df['phrases'].value_counts())
    result['Phrases with multiple labels'] = df1[df1['phrases'] > 1].shape[0]
    result['Min examples per label'] = df['labels'].value_counts().values.min()
    result['Max examples per label'] = df['labels'].value_counts().values.max()
    result['Avg examples per label'] = round(df['labels'].value_counts().mean(), 2)
    # appending the dictionary to dataframe
    result_df = result_df.append(result, ignore_index=True)

result_df = result_df.T
#result_df = result_df.astype({0: str, 1: str})
result_df.columns = ['TwADR-L', 'AskAPatient']

result_df

                              TwADR-L  AskAPatient
Unique_phrases                 616.00      2665.00
Unique_labels                   76.00       233.00
Unique_phrase_label_pairs      721.00      2686.00
Phrases with multiple labels    87.00        19.00
Min examples per label           5.00         5.00
Max examples per label          36.00       141.00
Avg examples per label           9.49        11.53